spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restful_api
    username: postgres
    password: Jahongir2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

elasticsearch:
  host: localhost
  port: 9200
